### PR TITLE
Strict typing for Typescript

### PR DESCRIPTION
**Pull request by singingwolfboy**
This project had some Typescript problems, so I fixed them as much as I could. Note that #16 should be merged before this pull request.

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Thanks for your interest in this project!

The description states that there’s typescript problems.  Per the contribution please start with an issue describing the problems before proceeding to coding.

The PR is also very hard to review with most lines changed due to line endings and other formatting changes.  

https://github.com/actions/http-client/blob/master/README.md#contributing

The PR should be scoped to the problems discussed in the issue.  The checks are also not passing.

**Comment by singingwolfboy** [comment]
> The PR is also very hard to review with most lines changed due to line endings and other formatting changes.

Yes, that's because of the Prettier changes in #16. As the description states, #16 should be merged first -- that will make this pull request much easier to read.

> The description states that there’s typescript problems. Per the contribution please start with an issue describing the problems before proceeding to coding.

The short version is that, because `strict` checks are turned off, it's not really possible to use this library in a project where `strict` checks are turned on. I'll make a separate issue or two to describe the problem more in-depth.

> The checks are also not passing.

Yes, I suspect the tests need to be modified as well to accommodate the stricter type checking, but I wasn't able to determine the best way to do so. Is it possible to work together with someone who has more experience with this code, to figure out how to do this?

**Comment by aminya** [comment]
Typescript issues still exist. @singingwolfboy Could you rebase?

**Comment by singingwolfboy** [comment]
@aminya Unfortunately, I don't see a path forward for this work to be merged, so I'm going to leave it alone.

**Pull request closed without merging**
